<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DC4-QVM-TMQA-08" ignored="0" name="Regression 2" tests="1" failures="0" timestamp="28 Sep 2018 10:33:58 GMT" time="47.722" errors="0">
  <testcase name="@AfterMethod tearDown" time="0.0" classname="generic.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at generic.BaseTest.tearDown(BaseTest.java:346)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterClass tearDown" time="0.0" classname="generic.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="testValidLogin2" time="44.049" classname="com.pulse.Test.ValidLogin2"/>
</testsuite> <!-- Regression 2 -->
